### ISSUE TITLE
Can't get simple "getting started" app to work

### ISSUE THREAD

**Issue by darrencruse** [flutter2js/flutter2js#6]
Fairly new to flutter and dart hopefully this is a mistake I'm making but fwiw I was attempting to follow your README instructions against a minimal app such as output from the flutter getting started tutorial i.e.:

https://flutter.io/get-started/test-drive/#create-app

I'm getting a "Could not find '.packages'." error from the flutter2js step.
(then errors on the pub get and pub serve steps don't know if they are a result of the can't find .packages error or not)

This is the command I used (is app-uri a file path do I have that wrong maybe?):

    pub global run flutter2js create example --app-name=myapp --app-uri=.

JIC it helps here's a copy/paste of my entire terminal session (I've bolded the errors):
```
$ pub global activate --source git https://github.com/jban332/flutter2js
Package flutter2js is currently active from Git repository "https://github.com/jban332/flutter2js".
Resolving dependencies... (1.0s)
+ args 1.4.3
+ flutter 0.0.20
+ flutter2js 0.2.0 from git https://github.com/jban332/flutter2js at d0fd19
+ meta 1.1.5
Precompiling executables...
Precompiled flutter2js:flutter2js.
Installed executable flutter2js.
Activated flutter2js 0.2.0 from Git repository "https://github.com/jban332/flutter2js".

$ cd myapp/
$ pub global run flutter2js create example --app-name=myapp --app-uri=.
Creating project 'example'.
Ok.

Running 'pub get'...

**Could not find '.packages'.**

$ ls -al .packages
-rw-r--r--  1 crused  staff  5368 May 14 19:05 .packages

$ ls example/
dart_test.yaml	pubspec.yaml	test		web

$ cd example/
$ pub get
Resolving dependencies... (1.8s)
**Because every version of flutter from git depends on flutter2js any which is forbidden, flutter from git is forbidden.
So, because example depends on flutter from git, version solving failed.**

$ pub serve
**Dart 2 has a new build system. Learn how to migrate from pub build and
pub serve: https://webdev.dartlang.org/dart-2**

$
```

**Comment by abnerh69** [comment]
Hi @darrencruse, Are you still trying with these tools?  I'm trying updating simple hello_world-browser sample to make it work.  Tried to contact @jban332 but not success.  Please, let me know if we can work together on this.

**Comment by darrencruse** [comment]
Apologies @abnerh69 I got busy and didn't see your comment till now.

To be honest I'm pretty new to (even) flutter and dart I'm doubting I can figure this out without help from @jban332 doubt I'm any help to your effort either...

Did you notice he *doesn't* check "Flutter SDK examples Work adequately" here:
https://github.com/flutter2js/flutter2js#status

So maybe things just aren't really working yet...  (looks like @jban332 is the lone contributor and I'm sure this is a very ambitious thing to make work!!  I wish google would take the idea seriously I think it would be the killer feature for flutter to run on android, iOS, and browser!!)

**Comment by abnerh69** [comment]
Thank you Darren,

I agree with your comments.  Please, let me know if there is a change to
make it work.  I am serious on it.  Thank you.
